<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-10-17 17:46
=======
# Generated by Django 3.2.8 on 2021-10-17 19:44
>>>>>>> 40ce046e69d06efcb4c7aef28d443182781cecae

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
