# Generated by Django 3.2.8 on 2021-10-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_subgroup_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='member',
            field=models.ManyToManyField(blank=True, to='group.SubGroup'),
        ),
    ]
