# Generated by Django 3.2.8 on 2021-10-11 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saidituser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidituser',
            name='member',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
