# Generated by Django 3.2.8 on 2021-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saidituser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidituser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saidituser',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='saidituser',
            name='display_name',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
    ]
