# Generated by Django 3.2.8 on 2021-10-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saidituser', '0002_saidituser_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidituser',
            name='member',
        ),
    ]
