# Generated by Django 3.2.8 on 2021-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saidituser', '0002_auto_20211005_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidituser',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
