# Generated by Django 3.2.8 on 2021-10-12 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saidituser', '0003_remove_saidituser_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidituser',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='_saidituser_saidituser_member_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
