# Generated by Django 3.2.8 on 2021-10-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.CharField(max_length=200),
        ),
    ]
