# Generated by Django 3.2.8 on 2021-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0003_alter_reply_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.TextField(),
        ),
    ]
